# Welcome to SES-Serverless-Application!
# 
# For full config options, check the docs:
#    docs.serverless.com
#

service: open-ses-service # NOTE: update this with your service name


provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SES_KEY: <AWS_KEY>
    SES_SECRET: <AWS_SECRET>
  throttle:
    # burstLimit: 2 sets the maximum short-term traffic volume for your network within a time interval
    burstLimit: 2
    # rateLimit: is the number of API calls allowed in a time interval in this case per second
    rateLimit: 1

plugins:
  - serverless-offline

functions:
  mailer:
    handler: handler.mailer

#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: /mail
          method: post
          cors: true

#    Define function environment variables here
    environment:
      SENDER_EMAIL: <my@verified.email>

